apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app:  javawebapp
spec:
  containers:
  - name: javawebappcontainer
    image: dockerhandson2/maven-web-app
    ports:
    - containerPort: 8080
